# Generated by Django 5.2.1 on 2025-05-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=2550)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('difficulty', models.CharField(blank=True, choices=[('Hard', 'Hard'), ('Easy', 'Easy'), ('Medium', 'Medium')], max_length=10)),
            ],
        ),
    ]
