# Generated by Django 5.2.1 on 2025-05-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='statement',
        ),
        migrations.AddField(
            model_name='problem',
            name='description',
            field=models.CharField(default='No description provided.', max_length=10000),
        ),
    ]
